
language: node_js

node_js:
  - 0.12.4

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
- npm -d install
- npm install -g grunt-cli
- npm install -g grunt

script:
- grunt
