
language: node_js

node_js:
  - 3.3.4

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
- npm -d install
- npm install -g grunt-cli
- npm install -g grunt

script:
- grunt

deploy:
- npm publish
